version: '3.7'

services:

  floodlight:
    build: ./floodlight
    privileged: true
    environment:
      - NO_CHECKSUMOFFLOAD_IFS=10.0.1.3
    networks:
      gns3-net:
        ipv4_address: 10.0.1.3
      floodlight-net:

  gns3:
    build: ./gns3
    ports:
      - 3080:3080
    privileged: true
    volumes:
      - gns3-data:/data
      - ./gns3/ANAWS.gns3:/data/projects/94c1d31d-2f0b-45be-9e8f-f9aeed10d4ec/ANAWS.gns3:rw
    networks:
      gns3-net:
        ipv4_address: 10.0.1.2
    depends_on:
      - floodlight
  
  webui:
    build: ./webui
    ports:
      - 8080:8080
    networks:
      - floodlight-net
    depends_on:
      - floodlight
    
volumes:
  gns3-data:

networks:
  gns3-net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  floodlight-net: